name: Docker Image CI

on:
  push:
    branches:
      - master  # Der Workflow wird bei jedem Push auf den 'master' Branch ausgeführt
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Schritt 1: Checkout des Repository-Codes
    - name: Checkout code
      uses: actions/checkout@v4

    # Schritt 2: Setze den Docker Buildx (optional, falls du Multi-Plattform Builds benötigst)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Schritt 3: Melde dich bei der GitHub Container Registry an
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Schritt 4: Baue das Docker-Image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/onionshare:v2.6.1

    # Schritt 5: Push das Docker-Image zu GitHub Container Registry
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/onionshare:v2.6.1

